package com.wcomp.app.tokens.handler

enum class ApplicationErrorCode() {
    CONNECT_ACCESS_TOKEN_ERROR,
    CONNECT_ACCOUNT_INFO_BAD_REQUEST,
    CONNECT_ACCOUNT_NOT_FOUND,
    CONNECT_BAD_REQUEST,
    CONNECT_ID_TOKEN_ERROR,
    CONNECT_INVALID_REFRESH_TOKEN,
    CONNECT_UNEXPECTED_ERROR,
    CONNECT_VALIDATION_ERROR
}